spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skeleton2
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      cache-null-values: true # null 캐싱 여부